export const PLACES: Array<{ place: string; timeZone: string }> = [
  { place: "Paris", timeZone: "Europe/Paris" },
  { place: "Rome", timeZone: "Europe/Rome" },
  { place: "Madrid", timeZone: "Europe/Madrid" },
  { place: "Lisbon", timeZone: "Europe/Lisbon" },
  { place: "Athens", timeZone: "Europe/Athens" },
  { place: "Istanbul", timeZone: "Europe/Istanbul" },
  { place: "Dubai", timeZone: "Asia/Dubai" },
  { place: "Delhi", timeZone: "Asia/Kolkata" },
  { place: "Bangkok", timeZone: "Asia/Bangkok" },
  { place: "Singapore", timeZone: "Asia/Singapore" },
  { place: "Bali", timeZone: "Asia/Makassar" },
  { place: "Hong Kong", timeZone: "Asia/Hong_Kong" },
  { place: "Tokyo", timeZone: "Asia/Tokyo" },
  { place: "Sydney", timeZone: "Australia/Sydney" },
  { place: "Melbourne", timeZone: "Australia/Melbourne" },
  { place: "Auckland", timeZone: "Pacific/Auckland" },
  { place: "New York", timeZone: "America/New_York" },
  { place: "Orlando", timeZone: "America/New_York" },
  { place: "Los Angeles", timeZone: "America/Los_Angeles" },
  { place: "Vancouver", timeZone: "America/Vancouver" },
  { place: "Honolulu", timeZone: "Pacific/Honolulu" },
  { place: "Cape Town", timeZone: "Africa/Johannesburg" },
  { place: "Marrakech", timeZone: "Africa/Casablanca" },
  { place: "Tenerife", timeZone: "Atlantic/Canary" },
  { place: "Maldives", timeZone: "Indian/Maldives" },
  { place: "Mauritius", timeZone: "Indian/Mauritius" },
  { place: "Reykjavik", timeZone: "Atlantic/Reykjavik" },
  { place: "Cyprus", timeZone: "Asia/Nicosia" },
];
